#!/bin/bash

hdir="$PWD"
dir="/tmp/s360"
pto="/tmp/s360.pto"
url="https://raw.githubusercontent.com/metalx1000/Samsung-Gear-360-Stitcher/master/ptos/hugin.pto"

#remove directory if it exists
if [ -d "$dir" ]
then
  echo "Working Directory Exists..."
  echo "Removing Directory..."
  rm -fr "$dir"
fi

#create Directory
echo "Creating Directory..."
mkdir -p "$dir" && echo "$dir created"

#checking for hugin file
if [ ! -f "$pto" ]
then
  echo "Downloading PTO file..."
  wget "$url" -O "$pto"
fi

#place pto in project folder
cp "$pto" "$dir/"

cp "$1" "$dir/"
#split image using imagemagick
convert "$1" -crop 50%x100% +repage /tmp/fe.png

#move to working dir
cd "$dir"
hugin_executor --stitching --prefix=pano_$1 "$pto"
cp $dir/*.png "$hdir"

xdg-open $dir/*.png
